# Generated by Django 2.2.16 on 2020-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenresBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=64, verbose_name='жанр книги')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
            ],
        ),
    ]
