# Generated by Django 2.2.16 on 2020-10-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenresBooks',
            new_name='GenreBooks',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='книга')),
                ('author', models.CharField(max_length=64, verbose_name='автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=64, verbose_name='краткое описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='цена')),
                ('count_page', models.PositiveSmallIntegerField(default=0, verbose_name='количество страниц')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('genre_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GenreBooks')),
            ],
        ),
    ]
