# Generated by Django 2.2.16 on 2020-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201031_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterModelOptions(
            name='genrebooks',
            options={'verbose_name': 'жанр книг', 'verbose_name_plural': 'жанры книг'},
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='books_images'),
        ),
    ]
