# Generated by Django 2.2.16 on 2020-11-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201108_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
        migrations.AddField(
            model_name='genrebooks',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность'),
        ),
    ]
