# Generated by Django 2.2.16 on 2020-11-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
    ]
